# Generated by Django 3.2.7 on 2021-09-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('github_url', models.TextField()),
                ('live_url', models.TextField()),
                ('linkedin_url', models.TextField()),
                ('youtube_url', models.TextField()),
                ('image_url', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
