# Generated by Django 3.2.7 on 2021-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='youtube_url',
            field=models.TextField(blank=True),
        ),
    ]
