# Generated by Django 3.2.7 on 2021-09-26 08:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0003_alter_posts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
