# Generated by Django 3.2.7 on 2021-09-26 18:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0004_alter_posts_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=255)),
                ('focusDefinition', models.TextField()),
                ('focusContent', ckeditor.fields.RichTextField()),
                ('focusLinks', models.CharField(blank=True, max_length=255)),
                ('focusImages', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
