# Generated by Django 3.2.7 on 2021-09-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0005_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=155)),
                ('lastName', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=155)),
            ],
        ),
    ]
