# Generated by Django 3.2.7 on 2021-09-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
