# Generated by Django 3.2.7 on 2021-09-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0009_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='live_url',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='youtube_url',
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
