# Generated by Django 3.2.7 on 2021-10-01 18:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0011_remove_posts_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
